name: WorldManagement
main: de.fileinputstream.mytraz.worldmanagement.Bootstrap
version: 1.0
description: world management
author: FileInputStream

commands:

    tpworld:

    createworld:

    removeresident:

    addresident:

    acceptinvite:

    newworldspawn:

    worldinfo:

    worlds:

    setpvp:

    tutorial:





